// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Falls back to the same default as .env.example so the CLI still works
    // if DATABASE_URL isn't set in the environment for some reason.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
